### ISSUE TITLE
Load error sometimes 

### ISSUE THREAD

**Issue by meowovo** [HebiRobotics/MFL#58] opened 2020-01-14 03:55 UTC
When I load a xx.mat file generated by MFL using MatLab,It may cause error"Unable to read mat file: ****.mat
file maybe corrupt".
And if I read the .mat using MFL,the
"Caused by: java.lang.IllegalArgumentException: Unknown tag type for id: 0
	at us.hebi.matlab.mat.format.Mat5Type.fromId(Mat5Type.java:232)
	at us.hebi.matlab.mat.format.Mat5Tag.readTag(Mat5Tag.java:103)
	at us.hebi.matlab.mat.format.Mat5Tag.readTagOrNull(Mat5Tag.java:80)
	at us.hebi.matlab.mat.format.Mat5Reader.readMatContent(Mat5Reader.java:229)
	at us.hebi.matlab.mat.format.Mat5Reader.readMat(Mat5Reader.java:194)"
exception will be shown.

source.readInt() == 251658240 

so packed =  true (because source.readInt()>>16 != 0)

what the PACK 's meaning?

Do I need to attach a Mat5Type anywhere?

Thanks!

**Comment by ennerf** [comment] 2020-01-14 12:13
How are you generating the mat files? It'd be great if you could provide some code to reproduce this problem. 

Is it possible that you are writing it without the 128 byte file header?

**Comment by ennerf** [comment] 2020-01-14 12:13
Packed refers to the [Small Data Element Format](https://www.mathworks.com/help/pdf_doc/matlab/matfile_format.pdf):

![image](https://user-images.githubusercontent.com/5491587/72343559-73f83d00-36cf-11ea-886c-1d143d021f14.png)

**Comment by meowovo** [comment] 2020-01-15 06:46
[Example.zip](https://github.com/HebiRobotics/MFL/files/4063331/Example.zip)

Here is the example method.

We attampted using jmatio to write datas incrementally to existing entries but we found no solution.

Can MFL work ?

We split .mat file temporarily,if we can append datas to exsiting entries it will be better~~

**Comment by meowovo** [comment] 2020-01-15 07:04
We first create the .mat file using 
`Martrix matrix = Mat5.newMatrix(rows,2);  `
`for (int i = 0; i < rows; i ++){  `
 `    matrix.setDouble(0,0,1.0);//1.0 is a random double number  `
`    matrix.setDouble(0,1,1.0);  `
`}`  
`MatFile matFile = Mat5.newMatfile().addArray(entry.getKey(),matrix);  
`Mat5.writeToFile(matFile,targetFileName); `
After this small .mat file,we do what I showed you in the example.java WITHOUT the "!file.exists()" case to append entries. And we can read the .mat file...............
So any reason for this ...?
Thanks a lot for your patient reply ~~~~~

**Comment by ennerf** [comment] 2020-01-15 10:28
It looks like the issue is different endian-ness, i.e., the file gets created in `BIG_ENDIAN` (default of Java's byte buffer), but the append happens in `LITTLE_ENDIAN`.

I'll change the default behavior for mapped files to native-order to be consistent. Thanks for bringing this up!

For now you can fix your code by manually setting the endian-ness of the sink.

**Comment by meowovo** [comment] 2020-01-15 10:46
Thanks!
We will try it tomorrow because my partner closed the PC and I don't have his password __(:з」∠)_ .(In fact this is my first issue in GitHub hahaha and I'm kind of excited~ : ))))))) )
Hope you have a nice day!

**Comment by ennerf** [comment] 2020-01-15 10:48
You too! I'll close this issue for now, but feel free to re-open it in case this turns out not to be the problem.

**Closed by ennerf** 2020-01-15 10:48 UTC
